theme: jekyll-theme-slate
title: StarGen II
description: Realistic solar-systems generator. C++ Library & Windows application.
show_downloads: true

github:
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/